//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentExamGradingSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblStudent()
        {
            this.TblGrade = new HashSet<TblGrade>();
        }
    
        public int Id { get; set; }
        public string StdName { get; set; }
        public string StdSurname { get; set; }
        public string StdNumber { get; set; }
        public string StdPassword { get; set; }
        public string StdMail { get; set; }
        public string StdPicture { get; set; }
        public Nullable<int> StdDepartment { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual TblDepartment TblDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGrade> TblGrade { get; set; }
    }
}
